apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configtemplates.konfigurator.stakater.com
spec:
  group: konfigurator.stakater.com
  names:
    kind: ConfigTemplate
    listKind: ConfigTemplateList
    plural: configtemplates
    singular: configtemplate
  scope: Namespaced
  version: v1
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: konfigurator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: konfigurator
  template:
    metadata:
      labels:
        name: konfigurator
    spec:
      containers:
        - name: konfigurator
          image: docker.io/stakater/konfigurator:test
          command:
          - Konfigurator
          imagePullPolicy: Always
      serviceAccountName: konfigurator
      