apiVersion: apps/v1
kind: Deployment
metadata:
  name: Konfigurator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: Konfigurator
  template:
    metadata:
      labels:
        name: Konfigurator
    spec:
      containers:
        - name: Konfigurator
          image: stakater/konfigurator:dev
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - Konfigurator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "Konfigurator"
