---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: konfigurator
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: konfigurator-role
rules:
- apiGroups:
  - konfigurator.stakater.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: konfigurator-rolebinding
subjects:
- kind: ServiceAccount
  name: konfigurator
  namespace: default
roleRef:
  kind: Role
  name: konfigurator-role
  apiGroup: rbac.authorization.k8s.io