---
# Source: konfigurator/templates/operator.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: konfigurator
    group: com.stakater.platform
    provider: stakater
    version: 0.0.10
    chart: "konfigurator-0.0.10"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: konfigurator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konfigurator
      group: com.stakater.platform
      provider: stakater
  template:
    metadata:
      labels:
        app: konfigurator
        group: com.stakater.platform
        provider: stakater
    spec:
      containers:
        - name: konfigurator
          image: "stakater/konfigurator:0.0.10"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - Konfigurator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "konfigurator"
      serviceAccountName: konfigurator

---
# Source: konfigurator/templates/rbac.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: konfigurator
    group: com.stakater.platform
    provider: stakater
    version: 0.0.10
    chart: "konfigurator-0.0.10"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: konfigurator

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
    app: konfigurator
    group: com.stakater.platform
    provider: stakater
    version: 0.0.10
    chart: "konfigurator-0.0.10"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: konfigurator-role
rules:
- apiGroups:
  - konfigurator.stakater.com
  resources:
  - "*"
  verbs:
  - "*"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
    app: konfigurator
    group: com.stakater.platform
    provider: stakater
    version: 0.0.10
    chart: "konfigurator-0.0.10"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: konfigurator-role-binding
subjects:
- kind: ServiceAccount
  name: konfigurator
  namespace: default
roleRef:
  kind: Role
  name: konfigurator-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
    app: konfigurator
    group: com.stakater.platform
    provider: stakater
    version: 0.0.10
    chart: "konfigurator-0.0.10"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: konfigurator-default-cluster-role
rules:
- apiGroups:
  - ""
  - "extensions"
  resources:
  - pods
  - ingresses
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - "extensions"
  resources:
  - daemonsets
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - secrets
  verbs:
  - "*"
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
    app: konfigurator
    group: com.stakater.platform
    provider: stakater
    version: 0.0.10
    chart: "konfigurator-0.0.10"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: konfigurator-default-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: konfigurator
  namespace: default
roleRef:
  kind: ClusterRole
  name: konfigurator-default-cluster-role
  apiGroup: rbac.authorization.k8s.io

---
# Source: konfigurator/templates/crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: konfiguratortemplates.konfigurator.stakater.com
spec:
  group: konfigurator.stakater.com
  names:
    kind: KonfiguratorTemplate
    listKind: KonfiguratorTemplateList
    plural: konfiguratortemplates
    singular: konfiguratortemplate
  scope: Namespaced
  version: v1alpha1

