apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "labels.selector" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "labels.selector" . | indent 8 }}
    spec:
      containers:
        - name: {{ template "name" . }}
          image: "{{ .Values.konfigurator.image.name }}:{{ .Values.konfigurator.image.tag }}"
          imagePullPolicy: {{ .Values.konfigurator.image.pullPolicy }}
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - Konfigurator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "{{ template "name" . }}"
      serviceAccountName: {{ template "name" . }}
